
trigger:
  branches:
    include:
      - master  # or main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '.'
    ArtifactName: 'html-artifact'
    publishLocation: 'Container'
